/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { createProduct } from '../fn/product-controller/create-product';
import { CreateProduct$Params } from '../fn/product-controller/create-product';
import { deleteProduct } from '../fn/product-controller/delete-product';
import { DeleteProduct$Params } from '../fn/product-controller/delete-product';
import { getAllProducts } from '../fn/product-controller/get-all-products';
import { GetAllProducts$Params } from '../fn/product-controller/get-all-products';
import { getLowStockProducts } from '../fn/product-controller/get-low-stock-products';
import { GetLowStockProducts$Params } from '../fn/product-controller/get-low-stock-products';
import { getOutOfStockProducts } from '../fn/product-controller/get-out-of-stock-products';
import { GetOutOfStockProducts$Params } from '../fn/product-controller/get-out-of-stock-products';
import { getProductById } from '../fn/product-controller/get-product-by-id';
import { GetProductById$Params } from '../fn/product-controller/get-product-by-id';
import { getProductCountBySupplier } from '../fn/product-controller/get-product-count-by-supplier';
import { GetProductCountBySupplier$Params } from '../fn/product-controller/get-product-count-by-supplier';
import { ProductDto } from '../models/product-dto';

@Injectable({ providedIn: 'root' })
export class ProductControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getAllProducts()` */
  static readonly GetAllProductsPath = '/api/products';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllProducts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllProducts$Response(params?: GetAllProducts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductDto>>> {
    return getAllProducts(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllProducts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllProducts(params?: GetAllProducts$Params, context?: HttpContext): Observable<Array<ProductDto>> {
    return this.getAllProducts$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProductDto>>): Array<ProductDto> => r.body)
    );
  }

  /** Path part for operation `createProduct()` */
  static readonly CreateProductPath = '/api/products';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createProduct()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProduct$Response(params: CreateProduct$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductDto>> {
    return createProduct(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createProduct$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createProduct(params: CreateProduct$Params, context?: HttpContext): Observable<ProductDto> {
    return this.createProduct$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductDto>): ProductDto => r.body)
    );
  }

  /** Path part for operation `getProductById()` */
  static readonly GetProductByIdPath = '/api/products/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProductById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductById$Response(params: GetProductById$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductDto>> {
    return getProductById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProductById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductById(params: GetProductById$Params, context?: HttpContext): Observable<ProductDto> {
    return this.getProductById$Response(params, context).pipe(
      map((r: StrictHttpResponse<ProductDto>): ProductDto => r.body)
    );
  }

  /** Path part for operation `deleteProduct()` */
  static readonly DeleteProductPath = '/api/products/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteProduct()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteProduct$Response(params: DeleteProduct$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteProduct(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteProduct$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteProduct(params: DeleteProduct$Params, context?: HttpContext): Observable<void> {
    return this.deleteProduct$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getProductCountBySupplier()` */
  static readonly GetProductCountBySupplierPath = '/api/products/supplier-count';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProductCountBySupplier()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductCountBySupplier$Response(params?: GetProductCountBySupplier$Params, context?: HttpContext): Observable<StrictHttpResponse<{
[key: string]: number;
}>> {
    return getProductCountBySupplier(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProductCountBySupplier$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductCountBySupplier(params?: GetProductCountBySupplier$Params, context?: HttpContext): Observable<{
[key: string]: number;
}> {
    return this.getProductCountBySupplier$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
[key: string]: number;
}>): {
[key: string]: number;
} => r.body)
    );
  }

  /** Path part for operation `getOutOfStockProducts()` */
  static readonly GetOutOfStockProductsPath = '/api/products/out-of-stock';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOutOfStockProducts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOutOfStockProducts$Response(params?: GetOutOfStockProducts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductDto>>> {
    return getOutOfStockProducts(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOutOfStockProducts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOutOfStockProducts(params?: GetOutOfStockProducts$Params, context?: HttpContext): Observable<Array<ProductDto>> {
    return this.getOutOfStockProducts$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProductDto>>): Array<ProductDto> => r.body)
    );
  }

  /** Path part for operation `getLowStockProducts()` */
  static readonly GetLowStockProductsPath = '/api/products/low-stock';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getLowStockProducts()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLowStockProducts$Response(params?: GetLowStockProducts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductDto>>> {
    return getLowStockProducts(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getLowStockProducts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getLowStockProducts(params?: GetLowStockProducts$Params, context?: HttpContext): Observable<Array<ProductDto>> {
    return this.getLowStockProducts$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProductDto>>): Array<ProductDto> => r.body)
    );

  }

  updateProduct(id: number, product: { product: ProductDto }): Observable<ProductDto> {
    return this.http.put<ProductDto>(`${this.rootUrl}/api/products/products/${id}`, product);
  }

}
