/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Sale } from '../models/sale';
export interface Customer {
  address?: string;
  customerName?: string;
  email?: string;
  id?: number;
  phone?: string;
  sales?: Array<Sale>;
}
