/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CustomerDto {
  address?: string;
  customerName?: string;
  email?: string;
  id?: number;
  phone?: string;
}
