/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SupplierDto } from './supplier-dto';
export interface ProductDto {
  id?: number;
  name?: string;
  price: number;
  stockQuantity: number;
  stockThreshold?: number;
  supplier?: SupplierDto;
  isDeleted?: boolean;
}
