/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Supplier } from '../models/supplier';
export interface Product {
  id?: number;
  name?: string;
  price?: number;
  stockQuantity?: number;
  stockThreshold?: number;
  supplier?: Supplier;
}
