/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PurchaseItemDto {
  price?: number;
  productId: number | undefined;
  quantity?: number;
  stockThreshold?: number; // <-- Add this!
}
