/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Product } from '../models/product';
import { Supplier } from '../models/supplier';
export interface Purchase {
  approved?: boolean;
  autoOrder?: boolean;
  id?: number;
  invoiceNumber?: string;
  products?: Array<Product>;
  purchaseDate?: string;
  quantity?: number;
  status?: string;
  supplier?: Supplier;
  totalAmount?: number;
}
