/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CustomerDto } from '../models/customer-dto';
import { SaleitemDto } from '../models/saleitem-dto';
export interface SaleDto {
  amount: number;
  customer?: CustomerDto;
  id?: number;
  invoiceNumber?: string;
  saleDate: string;
  saleItems: Array<SaleitemDto>;
}
