/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Product } from '../models/product';
import { Sale } from '../models/sale';
export interface SaleItem {
  id?: number;
  price?: number;
  product?: Product;
  quantity?: number;
  sale?: Sale;
}
