/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SaleitemDto } from '../models/saleitem-dto';
export interface SaleDto {
  amount?: number;
  date?: string;
  saleItems?: Array<SaleitemDto>;
}
