/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Supplier {
  adresse?: string;
  contactPerson?: string;
  deleted?: boolean;
  email?: string;
  id?: number;
  name?: string;
  slug?: string;
  telephone?: string;
}
