/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SupplierDto {
  adresse?: string;
  contactPerson?: string;
  email?: string;
  id?: number;
  isDeleted?: boolean;
  name?: string;
  productIds?: Array<number>;
  slug?: string;
  telephone?: string;
}
