/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Product } from '../models/product';
export interface Supplier {
  adresse?: string;
  contactPerson?: string;
  deleted?: boolean;
  email?: string;
  id?: number;
  name?: string;
  products?: Array<Product>;
  slug?: string;
  telephone?: string;
}
