/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface AddSaleItem$Params {
  saleId: number;
  productId: number;
  quantity: number;
  price: number;
}

export function addSaleItem(http: HttpClient, rootUrl: string, params: AddSaleItem$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, addSaleItem.PATH, 'post');
  if (params) {
    rb.path('saleId', params.saleId, {});
    rb.query('productId', params.productId, {});
    rb.query('quantity', params.quantity, {});
    rb.query('price', params.price, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

addSaleItem.PATH = '/api/sales/{saleId}/items';
