/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Sale } from '../../models/sale';

export interface GetSaleByInvoiceNumber$Params {
  invoiceNumber: string;
}

export function getSaleByInvoiceNumber(http: HttpClient, rootUrl: string, params: GetSaleByInvoiceNumber$Params, context?: HttpContext): Observable<StrictHttpResponse<Sale>> {
  const rb = new RequestBuilder(rootUrl, getSaleByInvoiceNumber.PATH, 'get');
  if (params) {
    rb.path('invoiceNumber', params.invoiceNumber, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Sale>;
    })
  );
}

getSaleByInvoiceNumber.PATH = '/api/sales/invoice/{invoiceNumber}';
