/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductCategoryDto } from '../../models/product-category-dto';

export interface GetProductsByCategoryCount$Params {
}

export function getProductsByCategoryCount(http: HttpClient, rootUrl: string, params?: GetProductsByCategoryCount$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProductCategoryDto>>> {
  const rb = new RequestBuilder(rootUrl, getProductsByCategoryCount.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ProductCategoryDto>>;
    })
  );
}

getProductsByCategoryCount.PATH = '/api/products/category-count';
