spring:
  datasource:
    url: jdbc:postgresql://dpg-d1oqkrk9c44c73fuain0-a.oregon-postgres.render.com:5432/inventory_db_rp2a
    username: inventory_db_rp2a_user
    password: AYnfeIRuKsRY5Q6ytboWSOqHOn8En7Az
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: DEBUG
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 70000000000000
      refresh-token:
        expiration: 7000000000000
springdoc:
  default-produces-media-type: application/json

  swagger-ui:
      path: /swagger-ui.html
      enabled: true
  api-docs:
      enabled: true