/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PurchaseDto } from '../../models/purchase-dto';

export interface CreatePurchase$Params {
      body: PurchaseDto
}

export function createPurchase(http: HttpClient, rootUrl: string, params: CreatePurchase$Params, context?: HttpContext): Observable<StrictHttpResponse<PurchaseDto>> {
  const rb = new RequestBuilder(rootUrl, createPurchase.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PurchaseDto>;
    })
  );
}

createPurchase.PATH = '/api/purchases';
