/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CustomerDto } from '../models/customer-dto';
import { deleteCustomer } from '../fn/customer-controller/delete-customer';
import { DeleteCustomer$Params } from '../fn/customer-controller/delete-customer';
import { getAllCustomers } from '../fn/customer-controller/get-all-customers';
import { GetAllCustomers$Params } from '../fn/customer-controller/get-all-customers';
import { getCustomerByEmail } from '../fn/customer-controller/get-customer-by-email';
import { GetCustomerByEmail$Params } from '../fn/customer-controller/get-customer-by-email';
import { getCustomerByPhone } from '../fn/customer-controller/get-customer-by-phone';
import { GetCustomerByPhone$Params } from '../fn/customer-controller/get-customer-by-phone';
import { saveCustomer } from '../fn/customer-controller/save-customer';
import { SaveCustomer$Params } from '../fn/customer-controller/save-customer';
import { updateCustomer } from '../fn/customer-controller/update-customer';
import { UpdateCustomer$Params } from '../fn/customer-controller/update-customer';

@Injectable({ providedIn: 'root' })
export class CustomerControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `updateCustomer()` */
  static readonly UpdateCustomerPath = '/api/customers/edit';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateCustomer()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateCustomer$Response(params: UpdateCustomer$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomerDto>> {
    return updateCustomer(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateCustomer$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateCustomer(params: UpdateCustomer$Params, context?: HttpContext): Observable<CustomerDto> {
    return this.updateCustomer$Response(params, context).pipe(
      map((r: StrictHttpResponse<CustomerDto>): CustomerDto => r.body)
    );
  }

  /** Path part for operation `getAllCustomers()` */
  static readonly GetAllCustomersPath = '/api/customers';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllCustomers()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllCustomers$Response(params?: GetAllCustomers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CustomerDto>>> {
    return getAllCustomers(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllCustomers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllCustomers(params?: GetAllCustomers$Params, context?: HttpContext): Observable<Array<CustomerDto>> {
    return this.getAllCustomers$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CustomerDto>>): Array<CustomerDto> => r.body)
    );
  }

  /** Path part for operation `saveCustomer()` */
  static readonly SaveCustomerPath = '/api/customers';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `saveCustomer()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveCustomer$Response(params: SaveCustomer$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomerDto>> {
    return saveCustomer(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `saveCustomer$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  saveCustomer(params: SaveCustomer$Params, context?: HttpContext): Observable<CustomerDto> {
    return this.saveCustomer$Response(params, context).pipe(
      map((r: StrictHttpResponse<CustomerDto>): CustomerDto => r.body)
    );
  }

  /** Path part for operation `getCustomerByPhone()` */
  static readonly GetCustomerByPhonePath = '/api/customers/phone/{phone}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCustomerByPhone()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCustomerByPhone$Response(params: GetCustomerByPhone$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomerDto>> {
    return getCustomerByPhone(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCustomerByPhone$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCustomerByPhone(params: GetCustomerByPhone$Params, context?: HttpContext): Observable<CustomerDto> {
    return this.getCustomerByPhone$Response(params, context).pipe(
      map((r: StrictHttpResponse<CustomerDto>): CustomerDto => r.body)
    );
  }

  /** Path part for operation `getCustomerByEmail()` */
  static readonly GetCustomerByEmailPath = '/api/customers/email/{email}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCustomerByEmail()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCustomerByEmail$Response(params: GetCustomerByEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomerDto>> {
    return getCustomerByEmail(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCustomerByEmail$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCustomerByEmail(params: GetCustomerByEmail$Params, context?: HttpContext): Observable<CustomerDto> {
    return this.getCustomerByEmail$Response(params, context).pipe(
      map((r: StrictHttpResponse<CustomerDto>): CustomerDto => r.body)
    );
  }

  /** Path part for operation `deleteCustomer()` */
  static readonly DeleteCustomerPath = '/api/customers/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteCustomer()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCustomer$Response(params: DeleteCustomer$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return deleteCustomer(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteCustomer$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteCustomer(params: DeleteCustomer$Params, context?: HttpContext): Observable<void> {
    return this.deleteCustomer$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
